### ISSUE TITLE
Upgrading qtism major version?

### ISSUE THREAD

**Issue by kendaop** [oat-sa/lib-tao-qti#20]
Hi, I'm just wondering if there are any plans to upgrade the 'qtism/qtism' dependency major version? I'm looking to update some other TAO components, but that would require at least qtism version 4.1.0.

**Comment by krampstudio** [comment]
This is something we would like to do but would require a substantial effort to get in. I don't think there's a short term plan for that.

@bugalot can give you a more detailed answer if needed.

**Comment by julien-sebire** [comment]
Not applicable anymore.
